@baseUrl = https://localhost:8443

POST  {{baseUrl}}/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "id": "admin",
    "password": "admin"
}

###
POST  {{baseUrl}}/reports/infos/from/2022-01-14/to/2022-07-15 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "select": ["id", "car_number", "date_ymd"],
    "limits": 1
}

###

POST  {{baseUrl}}/cars/TESTCAR2/infos/4 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "select": ["is_sent_to_1c", "who_sent_to_1c"]
}

###

POST  {{baseUrl}}/cars/TESTCAR1/update1c/info/2 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "is_sent_to_1c": false
}

###

POST  {{baseUrl}}/cars/TESTCAR1/infos/61/photos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "select": ["url", "description", "created_at"]
}


###

POST  {{baseUrl}}/cars/like/33 HTTP/1.1
Content-Type: application/json
Accept: application/json


###

POST  {{baseUrl}}/cars/TESTCAR34/add/info HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "date_ymd": "2022-06-11",
  "ttype_id": 1,
  "code": "",
  "in_datetime": "2022-06-09T05:58",
  "out_datetime": null,
  "contragent": "+998-90-222-11-22",
  "driver_phone": "+998-90-111-11-11",
  "comment": null
}

###     

POST  {{baseUrl}}/cars/TESTCAR2/infos/4 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "count": "* as records",
    "select": "date_ymd",
    "groupBy": "date_ymd"
}

###

POST  {{baseUrl}}/cars HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "select": ["number"],
    "ddistinct": ["date_ymd"],
    "dwhere": ["CAR_NUMBER","GTESTCAR3"],
    "dwhere": ["date_ymd","2022-06-08"]
}


###

POST  {{baseUrl}}/cars/TESTCAR1/infos/ HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "where": ["date_ymd","2022-01-21"]
}

###

POST  {{baseUrl}}/logout HTTP/1.1
Content-Type: application/json
Accept: application/json

###

POST  {{baseUrl}}/checkLogin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "userId": "admin",
    "password": "admin"
}

###

POST  {{baseUrl}}/getTransportTypes HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "userId": "admin",
    "password": "admin"
}

### 

GET  {{baseUrl}}/cars/TESTCAR1 HTTP/1.1
Content-Type: application/json
Accept: application/json

####

GET  {{baseUrl}}/cars/invalidIoInfoId HTTP/1.1
Content-Type: application/json
Accept: application/json

###

POST  {{baseUrl}}/cars/TESTCAR2/infos HTTP/1.1
Content-Type: application/json
Accept: application/json


